### ISSUE TITLE
这个项目怎么启动啊

### ISSUE THREAD

**Issue by WThink3** [rongcloud/sealclass-web#1]
这个项目怎么启动啊

**Comment by shuise** [comment]
https://github.com/rongcloud/sealclass-web 这里不是有说明么？

**Comment by WThink3** [comment]
> https://github.com/rongcloud/sealclass-web 这里不是有说明么？

![image](https://user-images.githubusercontent.com/49060142/56626235-7ca57080-6673-11e9-9e5b-77f9bd76e496.png)
这几步没看太懂 前端没怎么接触过

**Comment by yuhongda0315** [comment]
建议使用 Nginx 做静态资源服务器，SSI 配置说明参考：http://www.nginx.cn/doc/standard/httpssi.html

**Comment by lt-fancy** [comment]
![image](https://user-images.githubusercontent.com/20636540/61844635-af5d4000-aed2-11e9-9685-5b0d4d808a86.png)
这是什么问题
