### ISSUE TITLE
mac下nginx，后端未启动https，一直卡在登录界面，有js报错

### ISSUE THREAD

**Issue by lt-fancy** [rongcloud/sealclass-web#2]
![image](https://user-images.githubusercontent.com/20636540/61844749-1c70d580-aed3-11e9-8996-16023e0d769d.png)

![image](https://user-images.githubusercontent.com/20636540/61844763-2db9e200-aed3-11e9-8ddb-64e8dd9ac786.png)

**Comment by shuise** [comment]
RTC 必须 https 协议

**Comment by YongHao0** [comment]
需要在融云开发者后台开通音视频服务后再使用
