### ISSUE TITLE
升级SDK导致的问题解决方案

### ISSUE THREAD

**Issue by LIU0472** [rongcloud/sealclass-web#3]
客服说这个DEMO的SDK版本比较旧了，让升级。升级后报错。
最终debug发现是protobuf版本引起的。
默认加载自己的protobuf
https://github.com/rongcloud/sealclass-web/blob/0b38b6cdfb7c1d169c0c94df4dc39c95b5cbe19a/attach/head-static.html#L11
IM的SDK会识别protobuf是否需要加载
https://github.com/rongcloud/sealclass-web/blob/0b38b6cdfb7c1d169c0c94df4dc39c95b5cbe19a/assets/js/RongIMLib-2.4.0.js#L2010
结果新的IM SDK用了版本不匹配的protobuf版本。导致报错

所以注释掉head-static.html中的protobuf引入就解决了

**Comment by YongHao0** [comment]
此问题已修复, 可下载最新代码体验
